{% set name = "django-flags" %}
{% set version = "5.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4d29cc8892c23c9f58676804edccd8822a3fb34458e3ac36deb1cf499c80f55e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.2
    # - pymdown-extensions >=4.11
    # - mkdocs-rtd-dropdown >=0.0.11
    # - mkdocs >=0.17
    # - jinja2 
    # - django-debug-toolbar 
    # - coverage 

test:
  imports:
    - flags
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cfpb/django-flags
  summary: Feature flags for Django projects
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
