# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-flags
  version: 5.2.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: a3aee5e0d11e24e35f5ae4a423d52cad721f639181c1b1251e0148d8530a3f81

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=63
    - setuptools-scm >=8
    - pip
    #- wheel
  run:
    - python >=${{ python_min }},<4.0
    - django >=4.2
    - jinja2
    - django-debug-toolbar
tests:
  - python:
      imports:
        - flags
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: Feature flags for Django projects
  license: CC0-1.0
  license_file: LICENSE
  homepage: https://github.com/cfpb/django-flags

extra:
  recipe-maintainers:
    - rxm7706
